### ISSUE TITLE
cannot exec into a container in a completed pod; current phase is Succeeded

### ISSUE THREAD

**Issue by AuroraLantean** [paritytech/zombienet#181]
I was following your guide https://paritytech.github.io/zombienet/docs/book/guide.html#example-4---small-network-with-cumulus-based-collator]
 launch the network using the following command:

```
./zombienet-linux -p kubernetes test zombienet/0001-small-network.feature
```
the above 0001 command works well. but for 0004 ...
```
./zombienet-linux -p kubernetes spawn zombienet/0004-small-network-cumulus.toml
```
I got this error: cannot exec into a container in a completed pod; current phase is Succeeded
How can I solve this?
Please advise on the following terminal output. Thank you

```
{
  name: 'alice',
  key: '2bd806c97f0e00af1a1fc3328fa763a9269723c8db8fac4f93af71db186d6e90',
  accounts: {
    seed: '0x77ebc9e29f1bb4c86c007f8dd4519e00f1dec35a6bc8f1471d97467b8bfd1cef',
    sr_account: {
      address: '5FR5yeWwQzQTR1JCPyHQ9qxEHXunaRBYA4nNeXJHqxBMCNzJ',
      publicKey: '0x944012752e2402f9d58504c147cc34c4615a6d1f748cc460278c7955fdf9c54b'
    },
    sr_stash: {
      address: '5FHxSbKvBKHLMJcnuUmZrfjkaG6fKK8pGn6mLmW1fZ1JY4Nx',
      publicKey: '0x8ecffcdd0c2388fed8789dadee6bdec99d9072fbb591509dfc108706cae45a36'
    },
    ed_account: {
      address: '5HQzPrHrXe1hdhAhhwMUoecifuNQBfq6WzXnJLdfZuebKQCH',
      publicKey: '0xeca5bef5f0bad1684b99604b5f1cd3dcda4f65bc9b504fd145112831f28679c5'
    },
    ec_account: { publicKey: [Uint8Array] }
  },
  command: 'polkadot',
  commandWithArgs: undefined,
  image: 'docker.io/paritypr/polkadot-debug:master',
  chain: 'rococo-local',
  validator: true,
  args: [ '-lparachain=debug' ],
  env: [
    { name: 'COLORBT_SHOW_HIDDEN', value: '1' },
    { name: 'RUST_BACKTRACE', value: 'FULL' }
  ],
  bootnodes: [],
  telemetryUrl: '',
  telemetry: false,
  prometheus: true,
  overrides: [],
  addToBootnodes: false,
  resources: undefined,
  zombieRole: 'node',
  group: 'alice'
}
{
  name: 'bob',
  key: '81b637d8fcd2c6da6359e6963113a1170de795e4b725b84d1e0b4cfd9ec58ce9',
  accounts: {
    seed: '0xa9dc8d5dcd6f4d33dbf5146c56ffe051b1d639e433e052e2520e55aef6866e38',
    sr_account: {
      address: '5DPVRami2vWuJXG3ZYo1Y2YWbhYTY6dXLAq1qGKNSaokCyti',
      publicKey: '0x3a900b68fcb390ae64d80bf36a5cb47e828985a1345e63644d34fab00fc76c7d'
    },
    sr_stash: {
      address: '5DPpZo2gf74Gr3CPMQVo3Fgyvr4jXhof6dQTvTkfLYTJbmAj',
      publicKey: '0x3ad07b1960f914234206d6fb24eb45883103e223f01a1b9e44d98ceb8c90c350'
    },
    ed_account: {
      address: '5Fhbkrd4fjg9WCNogtUifgUZ3mQsCntAbUj2Fo4ACL7LKTen',
      publicKey: '0xa0d83ec38579c005ac1da19b18a5711a3c19a62d2aa709325d02f3946af59a94'
    },
    ec_account: { publicKey: [Uint8Array] }
  },
  command: 'polkadot',
  commandWithArgs: undefined,
  image: 'docker.io/paritypr/polkadot-debug:5236-0.9.18-c55660e9-be16bd72',
  chain: 'rococo-local',
  validator: true,
  args: [ '-lparachain=debug', '--database=paritydb-experimental' ],
  env: [
    { name: 'COLORBT_SHOW_HIDDEN', value: '1' },
    { name: 'RUST_BACKTRACE', value: 'FULL' }
  ],
  bootnodes: [],
  telemetryUrl: '',
  telemetry: false,
  prometheus: true,
  overrides: [],
  addToBootnodes: false,
  resources: undefined,
  zombieRole: 'node',
  group: 'bob'
}
```

	 Using provider: kubernetes

	 Launching network under namespace: zombie-2ab54d809e43779433358d742d3175ce
		 Using temporary directory: /tmp/zombie-2ab54d809e43779433358d742d3175ce_-146626-JEiXxvHlqKdX

	launching temp pod with image docker.io/paritypr/polkadot-debug:master
		 with command: bash -c polkadot build-spec --chain rococo-local --disable-default-bootnode > /cfg/rococo-local-plain.json && until [ -f /tmp/finished.txt ]; do echo waiting for copy files to finish; sleep 1; done; echo copy files has finished
		temp pod is ready!

		🧹 Starting with a fresh authority set...
			  👤 Added Genesis Authority alice - 5FHxSbKvBKHLMJcnuUmZrfjkaG6fKK8pGn6mLmW1fZ1JY4Nx
			  👤 Added Genesis Authority bob - 5DPpZo2gf74Gr3CPMQVo3Fgyvr4jXhof6dQTvTkfLYTJbmAj

	launching temp-1 pod with image docker.io/parity/polkadot-collator:latest
		 with command: bash -c test-collator build-spec  --disable-default-bootnode > /cfg/rococo-local-plain.json && until [ -f /tmp/finished.txt ]; do echo waiting for copy files to finish; sleep 1; done; echo copy files has finished
		temp-1 pod is ready!

```Error: Command failed with exit code 1: kubectl --kubeconfig /home/user1/.kube/config --namespace zombie-2ab54d809e43779433358d742d3175ce cp temp-1:/cfg/rococo-local-plain.json /tmp/zombie-2ab54d809e43779433358d742d3175ce_-146626-JEiXxvHlqKdX/rococo-local-2000-plain.json -c temp-1
error: cannot exec into a container in a completed pod; current phase is Succeeded
    at makeError (/snapshot/zombienet/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/snapshot/zombienet/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 1: kubectl --kubeconfig /home/user1/.kube/config --namespace zombie-2ab54d809e43779433358d742d3175ce cp temp-1:/cfg/rococo-local-plain.json /tmp/zombie-2ab54d809e43779433358d742d3175ce_-146626-JEiXxvHlqKdX/rococo-local-2000-plain.json -c temp-1',
  command: 'kubectl --kubeconfig /home/user1/.kube/config --namespace zombie-2ab54d809e43779433358d742d3175ce cp temp-1:/cfg/rococo-local-plain.json /tmp/zombie-2ab54d809e43779433358d742d3175ce_-146626-JEiXxvHlqKdX/rococo-local-2000-plain.json -c temp-1',
  escapedCommand: 'kubectl --kubeconfig "/home/user1/.kube/config" --namespace zombie-2ab54d809e43779433358d742d3175ce cp "temp-1:/cfg/rococo-local-plain.json" "/tmp/zombie-2ab54d809e43779433358d742d3175ce_-146626-JEiXxvHlqKdX/rococo-local-2000-plain.json" -c temp-1',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'error: cannot exec into a container in a completed pod; current phase is Succeeded',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

	 Node's logs are available in /tmp/zombie-2ab54d809e43779433358d742d3175ce_-146626-JEiXxvHlqKdX/logs
```

**Comment by pepoviola** [comment]
Hi @AuroraLantean, thanks for your feedback. From the logs looks like you have set the `command` of the collator to be `test-collator` **but** the image (polkadot-collator:latest) doesn't have this binary. The command **should be** `polkadot-collator` if you are using this image.

> launching temp-1 pod with image docker.io/parity/polkadot-collator:latest
	 with command: bash -c test-collator build-spec  --disable-default-bootnode > /cfg/rococo-local-plain.json && until [ -f /tmp/finished.txt ]; do echo waiting for copy files to finish; sleep 1; done; echo copy files has finished
	temp-1 pod is ready!

Can you post here your network spec (`.toml`) file to review.

Thanks again for your feedback.

**Comment by AuroraLantean** [comment]
Hi @pepoviola , thanks for the quick reply. I copied it from the guide... Please advise. Thanks
```
[relaychain]
default_image = "docker.io/paritypr/polkadot-debug:master"
default_command = "polkadot"
default_args = [ "-lparachain=debug" ]

chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  image = "docker.io/paritypr/polkadot-debug:5236-0.9.18-c55660e9-be16bd72"
  validator = true
  args = ["--database=paritydb-experimental"]

[[parachains]]
id = 2000
cumulus_based = true
genesis_wasm_generator = "test-collator export-genesis-wasm"
genesis_state_generator = "test-collator export-genesis-state"

  [parachains.collator]
  name = "collator01"
  image = "docker.io/parity/polkadot-collator:latest"
  command = "test-collator"
  args = ["-lparachain=debug"]
```

**Comment by pepoviola** [comment]
Hi @AuroraLantean, thanks for the feedback. The config of `examples/0004-small-network-cumulus.toml` is wrong, I will update asap to:

```toml
[relaychain]
default_image = "docker.io/paritypr/polkadot-debug:master"
default_command = "polkadot"
default_args = [ "-lparachain=debug" ]

chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  image = "docker.io/paritypr/polkadot-debug:5236-0.9.18-c55660e9-be16bd72"
  validator = true
  args = ["--database=paritydb-experimental"]

[[parachains]]
id = 100
cumulus_based = true

  [parachains.collator]
  name = "collator01"
  image = "docker.io/parity/polkadot-collator:latest"
  command = "polkadot-collator"
  args = ["-lparachain=debug"]
```

can you try with this config?
Thanks!

**Comment by AuroraLantean** [comment]
Hello @pepoviola , I just tried it... it showed this```Error: Invalid chain spec raw file generated``` then it exited out by itself.

```
		  ✓ Added Genesis Parachain 100

	launching temp-3 pod with image docker.io/paritypr/polkadot-debug:master
		 with command: bash -c polkadot build-spec --chain /cfg/rococo-local-plain.json --disable-default-bootnode  --raw > /cfg/rococo-local-raw.json && until [ -f /tmp/finished.txt ]; do echo waiting for copy files to finish; sleep 1; done; echo copy files has finished
uploading to fileserver: /tmp/zombie-acbb04c675c8225c33199e1326d16e3f_-236132-eAIEYutKnO2q/rococo-local-plain.json as:7ed8f63c772820a956828a3dd89d9c845691a5510e1d300d92e214618028e6c6
		temp-3 pod is ready!
Error: Invalid chain spec raw file generated.
    at /snapshot/zombienet/dist/providers/k8s/chain-spec.js:102:19
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/zombienet/dist/providers/k8s/chain-spec.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

	 Node's logs are available in /tmp/zombie-acbb04c675c8225c33199e1326d16e3f_-236132-eAIEYutKnO2q/logs
```

**Comment by AuroraLantean** [comment]
Somehow it is working now. I don't know what happened. Thank you

**Comment by pepoviola** [comment]
Hi @AuroraLantean, those two settings are *connected* because `cumulus_based` is a *flag* to make ZombieNet use the `cmd` from cumulus **but** the image should have a compatible binary.

Thanks!

**Comment by pepoviola** [comment]
Hi @AuroraLantean, closing this one feel free to reopen if you have questions.
Thanks for your feedback!

**Comment by AuroraLantean** [comment]
@pepoviola Okay please close this. Thank you!
