### ISSUE TITLE
Timeout(300) for transfer container for pod : temp

### ISSUE THREAD

**Issue by AuroraLantean** [paritytech/zombienet#202]
It seems I can only run zombienet in the terminal that has run `minikube start` already.
```
😄  minikube v1.25.2 on Linuxmint 20.3
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔄  Restarting existing docker container for "minikube" ...
🐳  Preparing Kubernetes v1.23.3 on Docker 20.10.12 ...
    ▪ kubelet.housekeeping-interval=5m
🔎  Verifying Kubernetes components...
    ▪ Using image kubernetesui/dashboard:v2.3.1
    ▪ Using image kubernetesui/metrics-scraper:v1.0.7
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass, dashboard
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```
When I ran a zombienet command in another terminal:
`./zombienet-linux -p kubernetes spawn zombienet/0001-small-network.toml`
then I got this:
```
Error: Timeout(300) for transfer container for pod : temp
    at KubeClient.<anonymous> (/snapshot/zombienet/dist/providers/k8s/kubeClient.js:181:19)
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/zombienet/dist/providers/k8s/kubeClient.js:5:58)
```

**Comment by pepoviola** [comment]
Hi @AuroraLantean, can you check the access to the cluster with the following command

```
kubectl config current-context
```
Or check the available contexts with
```
kubectl config get-contexts
```

Thanks!

**Comment by AuroraLantean** [comment]
Hi @pepoviola Please have a look below
```
$ kubectl config current-context
minikube

$ kubectl config get-contexts
CURRENT   NAME       CLUSTER    AUTHINFO   NAMESPACE
*        minikube    minikube    minikube   default
```

Then I ran my test:
```
small network( Small Network test )
runningNetworkSpecPath undefined
	 Launching network... this can take a while.

	 Using provider: kubernetes

	 Launching network under namespace: zombie-bac150e6b631124f1aa757b9eb19953f
		 Using temporary directory: /tmp/zombie-bac150e6b631124f1aa757b9eb19953f_-77106-yP5Q4nzU82Xg

	launching temp pod with image docker.io/parity/polkadot:v0.9.18
		 with command: bash -c polkadot build-spec --chain rococo-local --disable-default-bootnode > /cfg/rococo-local-plain.json && until [ -f /tmp/finished.txt ]; do echo waiting for copy files to finish; sleep 1; done; echo copy files has finished
		temp pod is ready!

		🧹 Starting with a fresh authority set...
			  👤 Added Genesis Authority alice - 5GNJqTPyNqANBkUVMN1LPPrxXnFouWXoe2wNSmmEoLctxiZY
			  👤 Added Genesis Authority bob - 5HpG9w8EBLe5XCrbczpwq5TSXvedjrBGCwqxK1iQ7qUsSWFc

	launching temp-1 pod with image gcr.io/paid-network-202104/collator:latest
		 with command: bash -c target/release/parachain-collator build-spec  --disable-default-bootnode > /cfg/rococo-local-plain.json && until [ -f /tmp/finished.txt ]; do echo waiting for copy files to finish; sleep 1; done; echo copy files has finished
Error: Timeout(300) for pod : temp-1
    at KubeClient.<anonymous> (/snapshot/zombienet/dist/providers/k8s/kubeClient.js:160:19)
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/zombienet/dist/providers/k8s/kubeClient.js:5:58)

	 Node's logs are available in /tmp/zombie-bac150e6b631124f1aa757b9eb19953f_-77106-yP5Q4nzU82Xg/logs
```
But I can run my test in the terminal that ran my `minikube start` first

**Comment by pepoviola** [comment]
Hi @AuroraLantean, did you still have this issue with the last version? I will close this one and feel free to re-open if needed.
Thanks!
