### ISSUE TITLE
Issue loading 0004-small-network-cumulus.toml

### ISSUE THREAD

**Issue by ddorgan** [paritytech/zombienet#216]
Checked out master and didn't make any changes. Getting an error with an example 0004-small-network-cumulus.toml:

```
$ node dist/cli.js  spawn examples/0004-small-network-cumulus.toml 

	 Using provider: kubernetes

	 Launching network under namespace: zombie-e8a4c376c485aea92a746acb52d825cf
		 Using temporary directory: /tmp/zombie-e8a4c376c485aea92a746acb52d825cf_-150131-UfZQ4kNqhlAV
	
	launching temp pod with image docker.io/paritypr/polkadot-debug:master
		 with command: bash -c polkadot build-spec --chain rococo-local --disable-default-bootnode > /cfg/rococo-local-plain.json && until [ -f /tmp/finished.txt ]; do echo waiting for copy files to finish; sleep 1; done; echo copy files has finished
		temp pod is ready!
Error: Command failed with exit code 1: kubectl --kubeconfig /home/davidd/.kube/config --namespace zombie-e8a4c376c485aea92a746acb52d825cf cp temp:/cfg/rococo-local-plain.json /tmp/zombie-e8a4c376c485aea92a746acb52d825cf_-150131-UfZQ4kNqhlAV/rococo-local-plain.json -c temp
error: unexpected EOF
tar: Removing leading `/' from member names
Dropping out copy after 0 retries
    at makeError (/home/davidd/dev/zombienet-master/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/davidd/dev/zombienet-master/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 1: kubectl --kubeconfig /home/davidd/.kube/config --namespace zombie-e8a4c376c485aea92a746acb52d825cf cp temp:/cfg/rococo-local-plain.json /tmp/zombie-e8a4c376c485aea92a746acb52d825cf_-150131-UfZQ4kNqhlAV/rococo-local-plain.json -c temp',
  command: 'kubectl --kubeconfig /home/davidd/.kube/config --namespace zombie-e8a4c376c485aea92a746acb52d825cf cp temp:/cfg/rococo-local-plain.json /tmp/zombie-e8a4c376c485aea92a746acb52d825cf_-150131-UfZQ4kNqhlAV/rococo-local-plain.json -c temp',
  escapedCommand: 'kubectl --kubeconfig "/home/davidd/.kube/config" --namespace zombie-e8a4c376c485aea92a746acb52d825cf cp "temp:/cfg/rococo-local-plain.json" "/tmp/zombie-e8a4c376c485aea92a746acb52d825cf_-150131-UfZQ4kNqhlAV/rococo-local-plain.json" -c temp',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: "tar: Removing leading `/' from member names\n" +
    'Dropping out copy after 0 retries',
  stderr: 'error: unexpected EOF',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

```

**Comment by ddorgan** [comment]
Have `polkadot` in $PATH
