### ISSUE TITLE
Error running on Apple M1

### ISSUE THREAD

**Issue by brunopgalvao** [paritytech/zombienet#288]
`zombienet-macos` binary was working fine on my mac a couple weeks ago when I last used it. Today when I executed the same binary I got the following error:

```
$ ./zombienet-macos 
pkg/prelude/bootstrap.js:1740
      throw error;
      ^

Error: dlopen(/var/folders/1d/6s8fc3sd60n73mhszqvnks8w0000gn/T/pkg/5a378a125ff5d76e9b0a6c87644ad38abb8a00fd30519238f991fff935cd81b1/napi-maybe-compressed-blob-darwin-x64/napi-maybe-compressed-blob.darwin-x64.node, 0x0001): tried: '/var/folders/1d/6s8fc3sd60n73mhszqvnks8w0000gn/T/pkg/5a378a125ff5d76e9b0a6c87644ad38abb8a00fd30519238f991fff935cd81b1/napi-maybe-compressed-blob-darwin-x64/napi-maybe-compressed-blob.darwin-x64.node' (no such file), '/private/var/folders/1d/6s8fc3sd60n73mhszqvnks8w0000gn/T/pkg/5a378a125ff5d76e9b0a6c87644ad38abb8a00fd30519238f991fff935cd81b1/napi-maybe-compressed-blob-darwin-x64/napi-maybe-compressed-blob.darwin-x64.node' (no such file)
    at process.dlopen (pkg/prelude/bootstrap.js:2114:28)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1719:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/snapshot/zombienet/node_modules/napi-maybe-compressed-blob/index.js:83:29)
    at Module._compile (pkg/prelude/bootstrap.js:1794:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  code: 'ERR_DLOPEN_FAILED'
}
````

This is happening with v1.2.54 as well as previous versions.

Looks like it is trying to find this file: `napi-maybe-compressed-blob.darwin-x64.node`.

```
$ rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/bruno/.rustup

installed toolchains
--------------------

stable-aarch64-apple-darwin (default)
stable-x86_64-apple-darwin
nightly-2022-02-10-x86_64-apple-darwin
nightly-2022-02-19-x86_64-apple-darwin
nightly-2022-02-20-x86_64-apple-darwin
nightly-2022-03-14-x86_64-apple-darwin
nightly-2022-04-01-x86_64-apple-darwin
nightly-x86_64-apple-darwin

active toolchain
----------------

stable-aarch64-apple-darwin (default)
rustc 1.63.0 (4b91a6ea7 2022-08-08)
```

> macOS Monterey v12.4

```
$ node --version
v16.14.2
```

**Comment by lemarier** [comment]
FYI I've bumped `pkg` to latest and it seems to be resolved from our side

**Comment by pepoviola** [comment]
> FYI I've bumped `pkg` to latest and it seems to be resolved from our side

Thanks for the feedback!

**Comment by pepoviola** [comment]
Closing here @brunopgalvao, please ping me if doesn't work for you the last version.
Thanks!
