### ISSUE TITLE
Error to run relay chain with parachain from cumulus repo (for custom `--chain` arg)

### ISSUE THREAD

**Issue by bkontur** [paritytech/zombienet#290]
I want to run relay chain + parachain with specific setup for `--chain=xyz-chain` from Cumulus repo,
I am using binaries built from source.

I see, at least these problems:
1. why `polkadot build-spec` and `polkadot-parachain build-spec` is trying to save configuration to the exact same file `/tmp/zombie-b8ed4b80f1caeb47b8e9ae6f092531f2_-197866-c08MBuBeGXcY/cfg/rococo-local-plain.json` ?
2. I need to run parachain.collator with arg `"--chain=xyz-chain"` , but this argument is not passed to the `polkadot-parachain build-spec` ? How can I fix/override this step?

**xyz.toml**

```
[relaychain]
default_command = "{{POLKADOT_BINARY_PATH}}"
default_args = [ "-lparachain=debug" ]

chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

  [[relaychain.nodes]]
  name = "charlie"
  validator = true

[[parachains]]
id = 1013
cumulus_based = true

  [[parachains.collators]]
  name = "alice"
  command = "{{POLKADOT_PARACHAIN_BINARY_PATH}}"
  args = ["-lparachain=debug", "--chain=xyz-chain"]

  [[parachains.collators]]
  name = "bob"
  command = "{{POLKADOT_PARACHAIN_BINARY_PATH}}"
  args = ["-lparachain=debug", "--chain=xyz-chain"]

  [[parachains.collators]]
  name = "charlie"
  command = "{{POLKADOT_PARACHAIN_BINARY_PATH}}"
  args = ["-lparachain=debug", "--chain=xyz-chain"]

```

**Run:**

```
POLKADOT_BINARY_PATH=./bin/polkadot \
	POLKADOT_PARACHAIN_BINARY_PATH=./bin/polkadot-parachain \
	./bin/zombienet-linux --provider native spawn xyz.toml
```

**Error:**
```
	 Using provider: native

	 Launching network under namespace: zombie-b8ed4b80f1caeb47b8e9ae6f092531f2
		 Using temporary directory: /tmp/zombie-b8ed4b80f1caeb47b8e9ae6f092531f2_-197866-c08MBuBeGXcY

	launching temp
		 with command: bash -c /home/bparity/local_bridge_testing/bin/polkadot build-spec --chain rococo-local --disable-default-bootnode > /tmp/zombie-b8ed4b80f1caeb47b8e9ae6f092531f2_-197866-c08MBuBeGXcY/cfg/rococo-local-plain.json
		temp is ready!

		🧹 Starting with a fresh authority set...
			  👤 Added Genesis Authority alice - 5GNJqTPyNqANBkUVMN1LPPrxXnFouWXoe2wNSmmEoLctxiZY
			  👤 Added Genesis Authority bob - 5HpG9w8EBLe5XCrbczpwq5TSXvedjrBGCwqxK1iQ7qUsSWFc
			  👤 Added Genesis Authority charlie - 5Ck5SLSHYac6WFt5UZRSsdJjwmpSZq85fd5TRNAdZQVzEAPT

	launching temp-1
		 with command: bash -c /home/bparity/local_bridge_testing/bin/polkadot-parachain build-spec  --disable-default-bootnode > /tmp/zombie-b8ed4b80f1caeb47b8e9ae6f092531f2_-197866-c08MBuBeGXcY/cfg/rococo-local-plain.json
Error: Command failed with exit code 101: /bin/bash -c /home/bparity/local_bridge_testing/bin/polkadot-parachain build-spec  --disable-default-bootnode > /tmp/zombie-b8ed4b80f1caeb47b8e9ae6f092531f2_-197866-c08MBuBeGXcY/cfg/rococo-local-plain.json
thread 'main' panicked at 'Failed to open file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', polkadot-parachain/src/command.rs:87:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    at makeError (/snapshot/zombienet/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/snapshot/zombienet/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 101: /bin/bash -c /home/bparity/local_bridge_testing/bin/polkadot-parachain build-spec  --disable-default-bootnode > /tmp/zombie-b8ed4b80f1caeb47b8e9ae6f092531f2_-197866-c08MBuBeGXcY/cfg/rococo-local-plain.json',
  command: '/bin/bash -c /home/bparity/local_bridge_testing/bin/polkadot-parachain build-spec  --disable-default-bootnode > /tmp/zombie-b8ed4b80f1caeb47b8e9ae6f092531f2_-197866-c08MBuBeGXcY/cfg/rococo-local-plain.json',
  escapedCommand: '"/bin/bash" -c "/home/bparity/local_bridge_testing/bin/polkadot-parachain build-spec  --disable-default-bootnode > /tmp/zombie-b8ed4b80f1caeb47b8e9ae6f092531f2_-197866-c08MBuBeGXcY/cfg/rococo-local-plain.json"',
  exitCode: 101,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: `thread 'main' panicked at 'Failed to open file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', polkadot-parachain/src/command.rs:87:46\n` +
    'note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Error: Command failed with exit code 101: /bin/bash -c /home/bparity/local_bridge_testing/bin/polkadot-parachain build-spec  --disable-default-bootnode > /tmp/zombie-b8ed4b80f1caeb47b8e9ae6f092531f2_-197866-c08MBuBeGXcY/cfg/rococo-local-plain.json
thread 'main' panicked at 'Failed to open file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', polkadot-parachain/src/command.rs:87:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    at makeError (/snapshot/zombienet/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/snapshot/zombienet/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 101: /bin/bash -c /home/bparity/local_bridge_testing/bin/polkadot-parachain build-spec  --disable-default-bootnode > /tmp/zombie-b8ed4b80f1caeb47b8e9ae6f092531f2_-197866-c08MBuBeGXcY/cfg/rococo-local-plain.json',
  command: '/bin/bash -c /home/bparity/local_bridge_testing/bin/polkadot-parachain build-spec  --disable-default-bootnode > /tmp/zombie-b8ed4b80f1caeb47b8e9ae6f092531f2_-197866-c08MBuBeGXcY/cfg/rococo-local-plain.json',
  escapedCommand: '"/bin/bash" -c "/home/bparity/local_bridge_testing/bin/polkadot-parachain build-spec  --disable-default-bootnode > /tmp/zombie-b8ed4b80f1caeb47b8e9ae6f092531f2_-197866-c08MBuBeGXcY/cfg/rococo-local-plain.json"',
  exitCode: 101,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: `thread 'main' panicked at 'Failed to open file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', polkadot-parachain/src/command.rs:87:46\n` +
    'note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

	 Node's logs are available in /tmp/zombie-b8ed4b80f1caeb47b8e9ae6f092531f2_-197866-c08MBuBeGXcY/logs
Error: Command failed with exit code 2: /bin/bash -c kill -9 
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
    at makeError (/snapshot/zombienet/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/snapshot/zombienet/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 2: /bin/bash -c kill -9 ',
  command: '/bin/bash -c kill -9 ',
  escapedCommand: '"/bin/bash" -c "kill -9 "',
  exitCode: 2,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
unhandledRejection
Error: Command failed with exit code 2: /bin/bash -c kill -9 
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
    at makeError (/snapshot/zombienet/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/snapshot/zombienet/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 2: /bin/bash -c kill -9 ',
  command: '/bin/bash -c kill -9 ',
  escapedCommand: '"/bin/bash" -c "kill -9 "',
  exitCode: 2,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

```

**Comment by bkontur** [comment]
ok, I was able to run it with:
```
[[parachains]]
...
chain=xyz-chain
```

but it needs to be updated here:
https://paritytech.github.io/zombienet/book/network-definition-spec.html

**Comment by pepoviola** [comment]
Hi @bkontur, thanks for the feedback! Yes, the docs are outdated at the moment. I will label this one as `documentation` to keep track. Let me know if you have questions or find something else.

**Comment by bkontur** [comment]
@pepoviola 
thank you, looks like everything else is working for me now

**Comment by pepoviola** [comment]
Hi @bkontur, closing here. Please re-open if needed.
Thanks!!
