### ISSUE TITLE
[Edited] Improve error log description - Global upload appears to start before upload of override binary

### ISSUE THREAD

**Issue by drahnr** [paritytech/zombienet#37]
```
cat ./zombienet_tests/parachains/0001-parachains-smoke-test.toml 
[settings]
timeout = 1000

[relaychain]
default_image = "{{ZOMBIENET_INTEGRATION_TEST_IMAGE}}"
chain = "rococo-local"
command = "polkadot"

  [[relaychain.nodes]]
  name = "alice"
  extra_args = [ "--alice" ]

  [[relaychain.nodes.env]]
  name = "RUST_LOG"
  value = "parachain=debug"

  [[relaychain.nodes.overrides]]
  local_path = "/media/supersonic1t/projects/parity/polkadot/target/release/polkadot"
  remote_name = "wonderland"

  [[relaychain.nodes]]
  name = "bob"
  extra_args = [ "--bob" ]

  [[relaychain.nodes.env]]
  name = "RUST_LOG"
  value = "parachain=debug"

  [[relaychain.nodes.overrides]]
  local_path = "/media/supersonic1t/projects/parity/polkadot/target/release/polkadot"
  remote_name = "builder"

[[parachains]]
id = 100
addToGenesis = false

  [parachains.collator]
  name = "collator01"
  image = "{{COL_IMAGE}}"
  command = "/usr/local/bin/adder-collator"

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"
```

---

```
DEBUG=zombie* node ../zombienet/dist/cli.js test ./zombienet_tests/parachains/0001-parachains-smoke-test.feature | tee log2.txt 2>&1  


  ( Smoke Test )
	 Launching network... this can take a while.
  zombie {
  zombie     "relaychain": {
  zombie         "defaultImage": "docker.io/paritypr/synth-wave:4555-0.9.13-acbc33c-e60ff27f",
  zombie         "nodes": [
  zombie             {
  zombie                 "name": "alice",
  zombie                 "command": "polkadot",
  zombie                 "image": "docker.io/paritypr/synth-wave:4555-0.9.13-acbc33c-e60ff27f",
  zombie                 "wsPort": 9933,
  zombie                 "port": 30333,
  zombie                 "chain": "rococo-local",
  zombie                 "args": [
  zombie                     "--alice"
  zombie                 ],
  zombie                 "env": [
  zombie                     {
  zombie                         "name": "COLORBT_SHOW_HIDDEN",
  zombie                         "value": "1"
  zombie                     },
  zombie                     {
  zombie                         "name": "RUST_BACKTRACE",
  zombie                         "value": "FULL"
  zombie                     },
  zombie                     {
  zombie                         "name": "RUST_LOG",
  zombie                         "value": "parachain=debug"
  zombie                     }
  zombie                 ],
  zombie                 "bootnodes": [
  zombie                     "/dns/bootnode/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
  zombie                 ],
  zombie                 "telemetryUrl": "",
  zombie                 "telemetry": false,
  zombie                 "prometheus": false,
  zombie                 "overrides": [
  zombie                     {
  zombie                         "local_path": "/media/supersonic1t/projects/parity/polkadot/target/release/polkadot",
  zombie                         "remote_name": "wonderland"
  zombie                     }
  zombie                 ]
  zombie             },
  zombie             {
  zombie                 "name": "bob",
  zombie                 "command": "polkadot",
  zombie                 "image": "docker.io/paritypr/synth-wave:4555-0.9.13-acbc33c-e60ff27f",
  zombie                 "wsPort": 9933,
  zombie                 "port": 30333,
  zombie                 "chain": "rococo-local",
  zombie                 "args": [
  zombie                     "--bob"
  zombie                 ],
  zombie                 "env": [
  zombie                     {
  zombie                         "name": "COLORBT_SHOW_HIDDEN",
  zombie                         "value": "1"
  zombie                     },
  zombie                     {
  zombie                         "name": "RUST_BACKTRACE",
  zombie                         "value": "FULL"
  zombie                     },
  zombie                     {
  zombie                         "name": "RUST_LOG",
  zombie                         "value": "parachain=debug"
  zombie                     }
  zombie                 ],
  zombie                 "bootnodes": [
  zombie                     "/dns/bootnode/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
  zombie                 ],
  zombie                 "telemetryUrl": "",
  zombie                 "telemetry": false,
  zombie                 "prometheus": false,
  zombie                 "overrides": [
  zombie                     {
  zombie                         "local_path": "/media/supersonic1t/projects/parity/polkadot/target/release/polkadot",
  zombie                         "remote_name": "builder"
  zombie                     }
  zombie                 ]
  zombie             }
  zombie         ],
  zombie         "chain": "rococo-local",
  zombie         "overrides": [],
  zombie         "chainSpecCommand": "polkadot build-spec --chain rococo-local --disable-default-bootnode"
  zombie     },
  zombie     "parachains": [
  zombie         {
  zombie             "id": 100,
  zombie             "addToGenesis": false,
  zombie             "collator": {
  zombie                 "name": "collator",
  zombie                 "command": "/usr/local/bin/adder-collator",
  zombie                 "image": "docker.io/paritypr/colander:4555-acbc33c9",
  zombie                 "chain": "rococo-local",
  zombie                 "args": [],
  zombie                 "env": [],
  zombie                 "bootnodes": [
  zombie                     "/dns/bootnode/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
  zombie                 ],
  zombie                 "substrateRole": "collator"
  zombie             },
  zombie             "genesisWasmGenerator": "/usr/local/bin/adder-collator export-genesis-wasm > /cfg/genesis-wasm",
  zombie             "genesisStateGenerator": "/usr/local/bin/adder-collator export-genesis-state > /cfg/genesis-state"
  zombie         }
  zombie     ],
  zombie     "settings": {
  zombie         "timeout": 1000
  zombie     },
  zombie     "types": {
  zombie         "Header": {
  zombie             "number": "u64",
  zombie             "parent_hash": "Hash",
  zombie             "post_state": "Hash"
  zombie         }
  zombie     }
  zombie } +0ms
  zombie 	 Temp Dir: /tmp/zombie-a54d098ddd6929d09a3209048a68ffbd_-3202409-arhLjcKHwch9 +3ms
	 Launching network under namespace: zombie-a54d098ddd6929d09a3209048a68ffbd
  zombie 	 Launching network under namespace: zombie-a54d098ddd6929d09a3209048a68ffbd +0ms
  zombie::kube::client {
  zombie::kube::client   apiVersion: 'v1',
  zombie::kube::client   kind: 'Namespace',
  zombie::kube::client   metadata: { name: 'zombie-a54d098ddd6929d09a3209048a68ffbd' }
  zombie::kube::client } +0ms
  zombie Creating bootnode and backchannel services +651ms
  zombie::kube::client launching temp pod with image docker.io/paritypr/synth-wave:4555-0.9.13-acbc33c-e60ff27f +4s
  zombie::kube::client command: bash -c polkadot build-spec --chain rococo-local --disable-default-bootnode > /cfg/rococo-local.json && until [ -f /tmp/finished.txt ]; do echo waiting for copy files to finish; sleep 1; done; echo copy files has finished +0ms
  zombie::kube::client {
  zombie::kube::client   apiVersion: 'v1',
  zombie::kube::client   kind: 'Pod',
  zombie::kube::client   metadata: {
  zombie::kube::client     name: 'temp',
  zombie::kube::client     labels: {
  zombie::kube::client       role: 'full-node',
  zombie::kube::client       app: 'zombienet',
  zombie::kube::client       'app.kubernetes.io/name': 'zombie-a54d098ddd6929d09a3209048a68ffbd',
  zombie::kube::client       'app.kubernetes.io/instance': 'temp'
  zombie::kube::client     },
  zombie::kube::client     annotations: { 'prometheus.io/scrape': 'true', 'prometheus.io/port': '9615' }
  zombie::kube::client   },
  zombie::kube::client   spec: {
  zombie::kube::client     hostname: 'temp',
  zombie::kube::client     containers: [ [Object] ],
  zombie::kube::client     initContainers: [ [Object] ],
  zombie::kube::client     restartPolicy: 'OnFailure',
  zombie::kube::client     volumes: [ [Object] ]
  zombie::kube::client   }
  zombie::kube::client } +364ms
  zombie::kube::client copyFileToPod [
  'cp',
  '/tmp/zombie-a54d098ddd6929d09a3209048a68ffbd_-3202409-arhLjcKHwch9/finished.txt',
  'temp:/tmp/finished.txt',
  '-c',
  'transfer-files-container'
] +3s
  zombie::kube::client { exitCode: 0, stdout: '' } +651ms
  zombie::kube::client temp pod is ready! +4s
  zombie::kube::chain-spec copy file from pod +0ms
  zombie::kube::client copyFileFromPod [
  'cp',
  'temp:/cfg/rococo-local.json',
  '/tmp/zombie-a54d098ddd6929d09a3209048a68ffbd_-3202409-arhLjcKHwch9/rococo-local.json',
  '-c',
  'temp'
] +1ms
  zombie::kube::client { exitCode: 0, stdout: "tar: Removing leading `/' from member names" } +2s
  zombie::kube::client copyFileToPod [
  'cp',
  '/tmp/zombie-a54d098ddd6929d09a3209048a68ffbd_-3202409-arhLjcKHwch9/finished.txt',
  'temp:/tmp/finished.txt',
  '-c',
  'temp'
] +1ms
  zombie::kube::client { exitCode: 0, stdout: '' } +625ms

🧹 Starting with a fresh authority set...
  👤 Added Genesis Authority alice - 5GNJqTPyNqANBkUVMN1LPPrxXnFouWXoe2wNSmmEoLctxiZY
  👤 Added Genesis Authority bob - 5HpG9w8EBLe5XCrbczpwq5TSXvedjrBGCwqxK1iQ7qUsSWFc
launching temp-collator pod with image docker.io/paritypr/colander:4555-acbc33c9
command: bash -c /usr/local/bin/adder-collator export-genesis-state > /cfg/genesis-state && /usr/local/bin/adder-collator export-genesis-wasm > /cfg/genesis-wasm && until [ -f /tmp/finished.txt ]; do echo waiting for copy files to finish; sleep 1; done; echo copy files has finished
  zombie::kube::client {
  zombie::kube::client   apiVersion: 'v1',
  zombie::kube::client   kind: 'Pod',
  zombie::kube::client   metadata: {
  zombie::kube::client     name: 'temp-collator',
  zombie::kube::client     labels: {
  zombie::kube::client       role: 'full-node',
  zombie::kube::client       app: 'zombienet',
  zombie::kube::client       'app.kubernetes.io/name': 'zombie-a54d098ddd6929d09a3209048a68ffbd',
  zombie::kube::client       'app.kubernetes.io/instance': 'temp-collator'
  zombie::kube::client     },
  zombie::kube::client     annotations: { 'prometheus.io/scrape': 'true', 'prometheus.io/port': '9615' }
  zombie::kube::client   },
  zombie::kube::client   spec: {
  zombie::kube::client     hostname: 'temp-collator',
  zombie::kube::client     containers: [ [Object] ],
  zombie::kube::client     initContainers: [ [Object] ],
  zombie::kube::client     restartPolicy: 'OnFailure',
  zombie::kube::client     volumes: [ [Object] ]
  zombie::kube::client   }
  zombie::kube::client } +802ms
  zombie::kube::client copyFileToPod [
  'cp',
  '/tmp/zombie-a54d098ddd6929d09a3209048a68ffbd_-3202409-arhLjcKHwch9/finished.txt',
  'temp-collator:/tmp/finished.txt',
  '-c',
  'transfer-files-container'
] +4s
  zombie::kube::client { exitCode: 0, stdout: '' } +635ms
  zombie::kube::client copyFileFromPod [
  'cp',
  'temp-collator:/cfg/genesis-state',
  '/tmp/zombie-a54d098ddd6929d09a3209048a68ffbd_-3202409-arhLjcKHwch9/100/genesis-state'
] +7s
  zombie::kube::client { exitCode: 0, stdout: '' } +395ms
  zombie::kube::client copyFileFromPod [
  'cp',
  'temp-collator:/cfg/genesis-wasm',
  '/tmp/zombie-a54d098ddd6929d09a3209048a68ffbd_-3202409-arhLjcKHwch9/100/genesis-wasm'
] +0ms
  zombie::kube::client { exitCode: 0, stdout: "tar: Removing leading `/' from member names" } +412ms
  zombie::kube::client copyFileToPod [
  'cp',
  '/tmp/zombie-a54d098ddd6929d09a3209048a68ffbd_-3202409-arhLjcKHwch9/finished.txt',
  'temp-collator:/tmp/finished.txt'
] +0ms
  zombie::kube::client { exitCode: 0, stdout: '' } +598ms
  zombie::kube::client launching temp-1 pod with image docker.io/paritypr/synth-wave:4555-0.9.13-acbc33c-e60ff27f +2ms
  zombie::kube::client command: bash -c polkadot build-spec --chain /cfg/rococo-local.json --disable-default-bootnode  --raw > /cfg/rococo-local-raw.json && until [ -f /tmp/finished.txt ]; do echo waiting for copy files to finish; sleep 1; done; echo copy files has finished +0ms
  zombie::kube::client {
  zombie::kube::client   apiVersion: 'v1',
  zombie::kube::client   kind: 'Pod',
  zombie::kube::client   metadata: {
  zombie::kube::client     name: 'temp-1',
  zombie::kube::client     labels: {
  zombie::kube::client       role: 'full-node',
  zombie::kube::client       app: 'zombienet',
  zombie::kube::client       'app.kubernetes.io/name': 'zombie-a54d098ddd6929d09a3209048a68ffbd',
  zombie::kube::client       'app.kubernetes.io/instance': 'temp-1'
  zombie::kube::client     },
  zombie::kube::client     annotations: { 'prometheus.io/scrape': 'true', 'prometheus.io/port': '9615' }
  zombie::kube::client   },
  zombie::kube::client   spec: {
  zombie::kube::client     hostname: 'temp-1',
  zombie::kube::client     containers: [ [Object] ],
  zombie::kube::client     initContainers: [ [Object] ],
  zombie::kube::client     restartPolicy: 'OnFailure',
  zombie::kube::client     volumes: [ [Object] ]
  zombie::kube::client   }
  zombie::kube::client } +395ms
  zombie::kube::client copyFileToPod [
  'cp',
  '/tmp/zombie-a54d098ddd6929d09a3209048a68ffbd_-3202409-arhLjcKHwch9/rococo-local.json',
  'temp-1:/cfg/rococo-local.json',
  '-c',
  'transfer-files-container'
] +4s
  zombie::kube::client { exitCode: 0, stdout: '' } +4s
  zombie::kube::client copyFileToPod [
  'cp',
  '/tmp/zombie-a54d098ddd6929d09a3209048a68ffbd_-3202409-arhLjcKHwch9/finished.txt',
  'temp-1:/tmp/finished.txt',
  '-c',
  'transfer-files-container'
] +1ms
  zombie::kube::client { exitCode: 0, stdout: '' } +670ms
  zombie::kube::client temp-1 pod is ready! +4s
  zombie::kube::chain-spec Getting the raw chain spec file from pod to the local environment. +28s
  zombie::kube::client copyFileFromPod [
  'cp',
  'temp-1:/cfg/rococo-local-raw.json',
  '/tmp/zombie-a54d098ddd6929d09a3209048a68ffbd_-3202409-arhLjcKHwch9/rococo-local.json',
  '-c',
  'temp-1'
] +0ms
  zombie::kube::client { exitCode: 0, stdout: "tar: Removing leading `/' from member names" } +2s
  zombie::kube::client copyFileToPod [
  'cp',
  '/tmp/zombie-a54d098ddd6929d09a3209048a68ffbd_-3202409-arhLjcKHwch9/finished.txt',
  'temp-1:/tmp/finished.txt',
  '-c',
  'temp-1'
] +3ms
  zombie::kube::client { exitCode: 0, stdout: '' } +521ms
  zombie Chain name: Rococo Local Testnet +43s
  zombie::kube::client launching bootnode pod with image docker.io/paritypr/synth-wave:4555-0.9.13-acbc33c-e60ff27f +1ms
  zombie::kube::client command: /cfg/zombie-wrapper.sh polkadot --chain /cfg/rococo-local.json --name bootnode --rpc-cors all --node-key 0000000000000000000000000000000000000000000000000000000000000001 --ws-external --rpc-external --listen-addr /ip4/0.0.0.0/tcp/30333 --no-mdns --no-telemetry +0ms
  zombie::kube::client {
  zombie::kube::client   apiVersion: 'v1',
  zombie::kube::client   kind: 'Pod',
  zombie::kube::client   metadata: {
  zombie::kube::client     name: 'bootnode',
  zombie::kube::client     labels: {
  zombie::kube::client       'app.kubernetes.io/name': 'zombie-a54d098ddd6929d09a3209048a68ffbd',
  zombie::kube::client       'app.kubernetes.io/instance': 'bootnode',
  zombie::kube::client       role: 'bootnode',
  zombie::kube::client       app: 'zombienet'
  zombie::kube::client     }
  zombie::kube::client   },
  zombie::kube::client   spec: {
  zombie::kube::client     hostname: 'bootnode',
  zombie::kube::client     containers: [ [Object] ],
  zombie::kube::client     initContainers: [ [Object] ],
  zombie::kube::client     restartPolicy: 'OnFailure',
  zombie::kube::client     volumes: [ [Object] ]
  zombie::kube::client   }
  zombie::kube::client } +404ms
  zombie::kube::client copyFileToPod [
  'cp',
  '/tmp/zombie-a54d098ddd6929d09a3209048a68ffbd_-3202409-arhLjcKHwch9/rococo-local.json',
  'bootnode:/cfg/rococo-local.json',
  '-c',
  'transfer-files-container'
] +4s
  zombie::kube::client { exitCode: 0, stdout: '' } +5s
  zombie::kube::client copyFileToPod [
  'cp',
  '/tmp/zombie-a54d098ddd6929d09a3209048a68ffbd_-3202409-arhLjcKHwch9/zombie-wrapper.sh',
  'bootnode:/cfg/zombie-wrapper.sh',
  '-c',
  'transfer-files-container'
] +0ms
  zombie::kube::client { exitCode: 0, stdout: '' } +651ms
  zombie::kube::client copyFileToPod [
  'cp',
  '/tmp/zombie-a54d098ddd6929d09a3209048a68ffbd_-3202409-arhLjcKHwch9/finished.txt',
  'bootnode:/tmp/finished.txt',
  '-c',
  'transfer-files-container'
] +1ms
  zombie::kube::client { exitCode: 0, stdout: '' } +651ms
  zombie::kube::client bootnode pod is ready! +4s
  zombie::port-forwarder stdout: Forwarding from 127.0.0.1:35777 -> 9944
  zombie::port-forwarder Forwarding from [::1]:35777 -> 9944
  zombie::port-forwarder  +0ms
  zombie::port-forwarder stdout: Forwarding from 127.0.0.1:41501 -> 9615
  zombie::port-forwarder Forwarding from [::1]:41501 -> 9615
  zombie::port-forwarder  +333ms
  zombie creating node: alice +21s
  zombie::kube::client launching alice pod with image docker.io/paritypr/synth-wave:4555-0.9.13-acbc33c-e60ff27f +6s
  zombie::kube::client command: /cfg/zombie-wrapper.sh polkadot --chain /cfg/rococo-local.json --name alice --rpc-cors all --alice --no-mdns --no-telemetry --bootnodes /dns/10.24.2.56/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp +0ms
  zombie::kube::client {
  zombie::kube::client   apiVersion: 'v1',
  zombie::kube::client   kind: 'Pod',
  zombie::kube::client   metadata: {
  zombie::kube::client     name: 'alice',
  zombie::kube::client     labels: {
  zombie::kube::client       role: 'full-node',
  zombie::kube::client       app: 'zombienet',
  zombie::kube::client       'app.kubernetes.io/name': 'zombie-a54d098ddd6929d09a3209048a68ffbd',
  zombie::kube::client       'app.kubernetes.io/instance': 'alice'
  zombie::kube::client     },
  zombie::kube::client     annotations: { 'prometheus.io/scrape': 'true', 'prometheus.io/port': '9615' }
  zombie::kube::client   },
  zombie::kube::client   spec: {
  zombie::kube::client     hostname: 'alice',
  zombie::kube::client     containers: [ [Object] ],
  zombie::kube::client     initContainers: [ [Object] ],
  zombie::kube::client     restartPolicy: 'OnFailure',
  zombie::kube::client     volumes: [ [Object] ]
  zombie::kube::client   }
  zombie::kube::client } +369ms
  zombie::kube::client copyFileToPod [
  'cp',
  '/tmp/zombie-a54d098ddd6929d09a3209048a68ffbd_-3202409-arhLjcKHwch9/rococo-local.json',
  'alice:/cfg/rococo-local.json',
  '-c',
  'transfer-files-container'
] +4s
  zombie::kube::client { exitCode: 0, stdout: '' } +4s
  zombie::kube::client copyFileToPod [
  'cp',
  '/tmp/zombie-a54d098ddd6929d09a3209048a68ffbd_-3202409-arhLjcKHwch9/zombie-wrapper.sh',
  'alice:/cfg/zombie-wrapper.sh',
  '-c',
  'transfer-files-container'
] +1ms
  zombie::kube::client { exitCode: 0, stdout: '' } +664ms
  zombie::kube::client copyFileToPod [
  'cp',
  '/media/supersonic1t/projects/parity/polkadot/target/release/polkadot',
  'alice:/cfg/wonderland',
  '-c',
  'transfer-files-container'
] +0ms
  zombie::kube::client { exitCode: 0, stdout: '' } +6m
  zombie::kube::client copyFileToPod [
  'cp',
  '/tmp/zombie-a54d098ddd6929d09a3209048a68ffbd_-3202409-arhLjcKHwch9/finished.txt',
  'alice:/tmp/finished.txt',
  '-c',
  'transfer-files-container'
] +0ms
  zombie::kube::client { exitCode: 0, stdout: '' } +544ms
  zombie::kube::client alice pod is ready! +3s
  zombie::port-forwarder stdout: Forwarding from 127.0.0.1:32993 -> 9944
  zombie::port-forwarder Forwarding from [::1]:32993 -> 9944
  zombie::port-forwarder  +6m
  zombie::port-forwarder stdout: Forwarding from 127.0.0.1:39755 -> 9615
  zombie::port-forwarder Forwarding from [::1]:39755 -> 9615
  zombie::port-forwarder  +226ms
  zombie creating node: bob +6m
  zombie::kube::client launching bob pod with image docker.io/paritypr/synth-wave:4555-0.9.13-acbc33c-e60ff27f +457ms
  zombie::kube::client command: /cfg/zombie-wrapper.sh polkadot --chain /cfg/rococo-local.json --name bob --rpc-cors all --bob --no-mdns --no-telemetry --bootnodes /dns/10.24.2.56/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp +0ms
  zombie::kube::client {
  zombie::kube::client   apiVersion: 'v1',
  zombie::kube::client   kind: 'Pod',
  zombie::kube::client   metadata: {
  zombie::kube::client     name: 'bob',
  zombie::kube::client     labels: {
  zombie::kube::client       role: 'full-node',
  zombie::kube::client       app: 'zombienet',
  zombie::kube::client       'app.kubernetes.io/name': 'zombie-a54d098ddd6929d09a3209048a68ffbd',
  zombie::kube::client       'app.kubernetes.io/instance': 'bob'
  zombie::kube::client     },
  zombie::kube::client     annotations: { 'prometheus.io/scrape': 'true', 'prometheus.io/port': '9615' }
  zombie::kube::client   },
  zombie::kube::client   spec: {
  zombie::kube::client     hostname: 'bob',
  zombie::kube::client     containers: [ [Object] ],
  zombie::kube::client     initContainers: [ [Object] ],
  zombie::kube::client     restartPolicy: 'OnFailure',
  zombie::kube::client     volumes: [ [Object] ]
  zombie::kube::client   }
  zombie::kube::client } +358ms
  zombie::kube::client copyFileToPod [
  'cp',
  '/tmp/zombie-a54d098ddd6929d09a3209048a68ffbd_-3202409-arhLjcKHwch9/rococo-local.json',
  'bob:/cfg/rococo-local.json',
  '-c',
  'transfer-files-container'
] +3s
  zombie::kube::client { exitCode: 0, stdout: '' } +4s
  zombie::kube::client copyFileToPod [
  'cp',
  '/tmp/zombie-a54d098ddd6929d09a3209048a68ffbd_-3202409-arhLjcKHwch9/zombie-wrapper.sh',
  'bob:/cfg/zombie-wrapper.sh',
  '-c',
  'transfer-files-container'
] +1ms
  zombie::kube::client { exitCode: 0, stdout: '' } +476ms
  zombie::kube::client copyFileToPod [
  'cp',
  '/media/supersonic1t/projects/parity/polkadot/target/release/polkadot',
  'bob:/cfg/wonderland',
  '-c',
  'transfer-files-container'
] +0ms
  zombie::kube::client { exitCode: 0, stdout: '' } +6m
  zombie::kube::client copyFileToPod [
  'cp',
  '/media/supersonic1t/projects/parity/polkadot/target/release/polkadot',
  'bob:/cfg/builder',
  '-c',
  'transfer-files-container'
] +0ms
uncaughtException
Error: GLOBAL TIMEOUT (1000 secs) 
    at Timeout._onTimeout (/media/supersonic1t/projects/parity/zombienet/dist/orchestrator.js:49:27)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
Error: GLOBAL TIMEOUT (1000 secs) 
    at Timeout._onTimeout (/media/supersonic1t/projects/parity/zombienet/dist/orchestrator.js:49:27)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

```

**Comment by pepoviola** [comment]
Hi @drahnr, closing this one. We had improved the error reporting. Please reopen if needed.
Thanks!!!
