### ISSUE TITLE
Setup issues

### ISSUE THREAD

**Issue by sacha-l** [paritytech/zombienet#393]
A list of issues I've run into when trying to set-up Zombienet locally. I'd like to take this opportunity to offer help in improving the setup and other instructions in the README and mdbook docs, while learning more in depth about using zombienet. Please use this issue to suggest things I may be doing wrong, or things that could be better clarified on what's already written.  

 1.  Installing `node dist/setup.js` gives me: 

```bash
Error: Cannot find module '/.../Zombienet/zombienet/dist/setup.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v17.5.0
```

I noticed that the correct command (as of [this PR](https://github.com/paritytech/zombienet/pull/351)) would be:

```bash
node dist/cli.js
```

And similarly, to setup the polkadot and parachain network you'd run:

```bash
node dist/cli.js setup polkadot parachain
```

2. `export PATH=/../Zombienet/zombienet/dist:$PATH` didn't work as expected.

Not sure what's missing in the docs but on a macOS running that command doesn't allow me to simply run: `./zombienet --help` 

3. Would be good to show where the binary is downloaded and specify via CLI ideally. For example:

```bash
Start download...

-> downloading [========================================] 100% 0.0s
Binary "polkadot-parachain" downloaded to `home/files/zombienet/binaries`
Giving permissions to "polkadot-parachain"
-> downloading [========================================] 100% 0.0s
Binary "polkadot" downloaded  to `home/files/zombienet/binaries`
Giving permissions to "polkadot"
```

4. Error when I run `node dist/cli.js -p "native" spawn examples/0001-small-network.toml`. Here's what I get:

```bash
╔════════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════╗
║ 🧟 Zombienet       │ Initiation                                                                                         ║
╟────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ Provider           │ native                                                                                             ║
╟────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ Namespace          │ zombie-179ea9ae1c23ffbc377bb51f7d4ecf21                                                            ║
╟────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ Temp Dir           │ /var/folders/7h/0j4x7w1d4hq76qt0n315k1m40000gn/T/zombie-179ea9ae1c23ffbc377bb51f7d4ecf21_-52908-J… ║
╚════════════════════╧════════════════════════════════════════════════════════════════════════════════════════════════════╝
Error: Command failed with exit code 126: /bin/bash -c polkadot build-spec --chain rococo-local --disable-default-bootnode > /var/folders/7h/0j4x7w1d4hq76qt0n315k1m40000gn/T/zombie-179ea9ae1c23ffbc377bb51f7d4ecf21_-52908-JEWGsDzPvj0a/cfg/rococo-local-plain.json
/bin/bash: /Users/sachalansky/Documents/GitHub/Zombienet/zombienet/dist/polkadot: cannot execute binary file
    at makeError (/Users/sachalansky/Documents/GitHub/Zombienet/zombienet/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/sachalansky/Documents/GitHub/Zombienet/zombienet/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 126: /bin/bash -c polkadot build-spec --chain rococo-local --disable-default-bootnode > /var/folders/7h/0j4x7w1d4hq76qt0n315k1m40000gn/T/zombie-179ea9ae1c23ffbc377bb51f7d4ecf21_-52908-JEWGsDzPvj0a/cfg/rococo-local-plain.json',
  command: '/bin/bash -c polkadot build-spec --chain rococo-local --disable-default-bootnode > /var/folders/7h/0j4x7w1d4hq76qt0n315k1m40000gn/T/zombie-179ea9ae1c23ffbc377bb51f7d4ecf21_-52908-JEWGsDzPvj0a/cfg/rococo-local-plain.json',
  escapedCommand: '"/bin/bash" -c "polkadot build-spec --chain rococo-local --disable-default-bootnode > /var/folders/7h/0j4x7w1d4hq76qt0n315k1m40000gn/T/zombie-179ea9ae1c23ffbc377bb51f7d4ecf21_-52908-JEWGsDzPvj0a/cfg/rococo-local-plain.json"',
  exitCode: 126,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '/bin/bash: /Users/sachalansky/Documents/GitHub/Zombienet/zombienet/dist/polkadot: cannot execute binary file',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

In this step, it also occurred to me that the default should probably be native.

**Comment by wirednkod** [comment]
Thank you Sacha.
Concerning your points:
1) indeed the setup was merged with the main `cli` and thus the documentation needs to be altered,
2) I have to revisit MacOS setup again. (e.g. polkadot binary does not exist in MacOS, PR #392 addresses that)
3) Im not sure if there is a need to do that - I mean the `export` command shows the directory where the files are located, but even if setup shows you were they are... what is the point? We can of course do that - I just do not find it that necessery
4) You cannot really run `polkadot` in MacOs as there is no binary given. PR #392 is providing a note for it (see screenshot in description). You will need to clone the repo and run it locally

**Comment by wirednkod** [comment]
I think now that #395 and #392 are merged this can close
