### ISSUE TITLE
Can not run zombienet-linux binary v1.2.80

### ISSUE THREAD

**Issue by haerdib** [paritytech/zombienet#493]
I tried to run `./zombienet-linux` of release [v.1.2.80](https://github.com/paritytech/zombienet/releases/tag/v1.2.80) on Ubuntu 20.04, but I got the following error:

```
$ ./zombienet-linux

pkg/prelude/bootstrap.js:1876
      throw error;
      ^

Error: Cannot find module '/snapshot/zombienet/node_modules/axios/dist/node/axios.cjs'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:960:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:953:15)
    at resolveExports (node:internal/modules/cjs/loader:482:14)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1855:31)
    at require (node:internal/modules/cjs/helpers:102:18) {
  code: 'MODULE_NOT_FOUND',
  path: '/snapshot/zombienet/node_modules/axios/package.json',
  pkg: true
}
```

It works without problems with the zombienet-linux binary from v1.2.73.

**Comment by wirednkod** [comment]
Thank you @haerdib for reporting this. Will look into it

**Comment by skunert** [comment]
Still experiencing similar issues with 1.3.2, which should include a fix as I understand.
Different error messages for testing and just spawning.
For spawning:
```
❯ zombienet --provider native spawn zombienet_tests/0006-rpc_collator_builds_blocks.toml
╔════════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════╗
║ 🧟 Zombienet 🧟    │ Initiation                                                                                         ║
╟────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ Provider           │ native                                                                                             ║
╟────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ Namespace          │ zombie-18adf43e5597cca85edadef6785e3d84                                                            ║
╟────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ Temp Dir           │ /tmp/zombie-18adf43e5597cca85edadef6785e3d84_-270817-oak3HJufrNXF                                  ║
╚════════════════════╧════════════════════════════════════════════════════════════════════════════════════════════════════╝
Error: File '/**/javascript/packages/orchestrator/zombie-wrapper.sh' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at error_ENOENT (pkg/prelude/bootstrap.js:657:19)
    at readFileFromSnapshot (pkg/prelude/bootstrap.js:1049:29)
    at Object.readFileSync (pkg/prelude/bootstrap.js:1097:18)
    at deflateSync (pkg/prelude/bootstrap.js:717:24)
    at uncompressExternally (pkg/prelude/bootstrap.js:732:25)
    at uncompressExternallyPath (pkg/prelude/bootstrap.js:745:12)
    at Object.readFile (pkg/prelude/bootstrap.js:1709:28)
    at /snapshot/javascript/packages/orchestrator/dist/orchestrator.js
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/javascript/packages/orchestrator/dist/orchestrator.js) {
  errno: -2,
  code: 'ENOENT',
  path: '/snapshot/javascript/packages/orchestrator/zombie-wrapper.sh',
  pkg: true
}
UnhandledRejection: TypeError: undefined is not a function
```

For testing:
```
❯ zombienet --provider native test ../cumulus/zombienet_tests/0002-pov_recovery.feature
UnhandledRejection: TypeError: Cannot find module '/snapshot/javascript/packages/orchestrator/dist/test-runner/testReporter'
Require stack:
- /snapshot/javascript/node_modules/mocha/lib/mocha.js
- /snapshot/javascript/node_modules/mocha/index.js
- /snapshot/javascript/packages/orchestrator/dist/test-runner/index.js
- /snapshot/javascript/packages/orchestrator/dist/index.js
- /snapshot/javascript/packages/cli/dist/cli.js
```

**Comment by skunert** [comment]
Can confirm, thanks!
