### ISSUE TITLE
Error: Log lines of process: 23963 ( node: bob-2 ) doesn't grow, please check logs at /tmp/zombie-9739371c38cee8945a1ec83410dd6a3c_-20963-ZvceLXDqoFwh/bob-2.log

### ISSUE THREAD

**Issue by dzmitry-lahoda** [paritytech/zombienet#636]
```
   │
├────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────┤
│ Status                                 │ Ready                                                                          │
└────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────┘
╔════════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════╗
║ Pod                │ dave                                                                                               ║
╟────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ Status             │ Running                                                                                            ║
╟────────────────────╧────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ You can follow the logs of the node by running this command:                                                            ║
╚═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
tail -f  /tmp/zombie-9739371c38cee8945a1ec83410dd6a3c_-20963-ZvceLXDqoFwh/dave.log


┌────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Pod                │ bob-1                                                                                              │
├────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Status             │ Launching                                                                                          │
├────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Command            │ /nix/store/bn6ippd563c3n2i61qnqbm6x86pjbhfn-cumulus-v0.9.27/bin/polkadot-parachain --              │
│                    │ name bob-1 --node-key a5fc3eac9107fe9b449965916d54b334233b8077a37f782d9b59e6e98e04def8 --c         │
│                    │ hain /tmp/zombie-9739371c38cee8945a1ec83410dd6a3c_-20963-ZvceLXDqoFwh/bob-1/cfg/statemine-         │
│                    │ local_rococo-local-1000.json --base-path /tmp/zombie-9739371c38cee8945a1ec83410dd6a3c_-209         │
│                    │ 63-ZvceLXDqoFwh/bob-1/data --listen-addr /ip4/0.0.0.0/tcp/39123/ws --rpc-port 37451 --ws-p         │
│                    │ ort 33291 --prometheus-external --prometheus-port 43573 --rpc-cors all --unsafe-rpc-extern         │
│                    │ al --rpc-methods unsafe --unsafe-ws-external --collator -- --chain /tmp/zombie-9739371c38c         │
│                    │ ee8945a1ec83410dd6a3c_-20963-ZvceLXDqoFwh/bob-1/cfg/rococo-local.json --execution wasm --p         │
│                    │ ort 32965 --ws-port 35207 --rpc-port 43819                                                         │
└────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────┘
┌────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────┐
│ Pod                                    │ bob-1                                                                          │
├────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────┤
│ Status                                 │ Ready                                                                          │
└────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────┘
╔════════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════╗
║ Pod                │ bob-1                                                                                              ║
╟────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ Status             │ Running                                                                                            ║
╟────────────────────╧────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ You can follow the logs of the node by running this command:                                                            ║
╚═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
tail -f  /tmp/zombie-9739371c38cee8945a1ec83410dd6a3c_-20963-ZvceLXDqoFwh/bob-1.log


┌────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Pod                │ charlie-1                                                                                          │
├────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Status             │ Launching                                                                                          │
├────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Command            │ /nix/store/bn6ippd563c3n2i61qnqbm6x86pjbhfn-cumulus-v0.9.27/bin/polkadot-parachain --              │
│                    │ name charlie-1 --node-key 60e70b8055017b7350526fbf4d99591c065ba0ef7fe1ea245bb82477d928b051         │
│                    │  --chain /tmp/zombie-9739371c38cee8945a1ec83410dd6a3c_-20963-ZvceLXDqoFwh/charlie-1/cfg/st         │
│                    │ atemine-local_rococo-local-1000.json --base-path /tmp/zombie-9739371c38cee8945a1ec83410dd6         │
│                    │ a3c_-20963-ZvceLXDqoFwh/charlie-1/data --listen-addr /ip4/0.0.0.0/tcp/41785/ws --rpc-port          │
│                    │ 35019 --ws-port 42029 --prometheus-external --prometheus-port 41271 --rpc-cors all --unsaf         │
│                    │ e-rpc-external --rpc-methods unsafe --unsafe-ws-external --collator -- --chain /tmp/zombie         │
│                    │ -9739371c38cee8945a1ec83410dd6a3c_-20963-ZvceLXDqoFwh/charlie-1/cfg/rococo-local.json --ex         │
│                    │ ecution wasm --port 43971 --ws-port 44891 --rpc-port 33843                                         │
└────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────┘
┌────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────┐
│ Pod                                    │ charlie-1                                                                      │
├────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────┤
│ Status                                 │ Ready                                                                          │
└────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────┘
╔════════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════╗
║ Pod                │ charlie-1                                                                                          ║
╟────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ Status             │ Running                                                                                            ║
╟────────────────────╧────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ You can follow the logs of the node by running this command:                                                            ║
╚═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
tail -f  /tmp/zombie-9739371c38cee8945a1ec83410dd6a3c_-20963-ZvceLXDqoFwh/charlie-1.log


┌────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Pod                │ bob-2                                                                                              │
├────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Status             │ Launching                                                                                          │
├────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Command            │ /nix/store/j33may0jyxyg2v89k7cixipfam0gz5f8-acala/bin/acala --name bob-2 --node-key a              │
│                    │ 9137698d8d3fdbf27efcdc8cd372084b52d484e8db866c5455bbb3f85299b54 --chain /tmp/zombie-973937         │
│                    │ 1c38cee8945a1ec83410dd6a3c_-20963-ZvceLXDqoFwh/bob-2/cfg/karura-dev_rococo-local-2000.json         │
│                    │  --base-path /tmp/zombie-9739371c38cee8945a1ec83410dd6a3c_-20963-ZvceLXDqoFwh/bob-2/data -         │
│                    │ -listen-addr /ip4/0.0.0.0/tcp/42449/ws --rpc-port 43289 --ws-port 35403 --prometheus-exter         │
│                    │ nal --prometheus-port 35057 --rpc-cors all --unsafe-rpc-external --rpc-methods unsafe --un         │
│                    │ safe-ws-external --collator -- --chain /tmp/zombie-9739371c38cee8945a1ec83410dd6a3c_-20963         │
│                    │ -ZvceLXDqoFwh/bob-2/cfg/rococo-local.json --execution wasm --port 44679 --ws-port 36833 --         │
│                    │ rpc-port 43399                                                                                     │
└────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────┘
Error: Log lines of process: 23963 ( node: bob-2 ) doesn't grow, please check logs at /tmp/zombie-9739371c38cee8945a1ec83410dd6a3c_-20963-ZvceLXDqoFwh/bob-2.log
    at NativeClient.<anonymous> (/nix/store/czwj2a7vlzhvz0aqhn82mcf72lp8r3a7-zombienet/packages/orchestrator/dist/providers/native/nativeClient.js:330:19)
    at Generator.next (<anonymous>)
    at fulfilled (/nix/store/czwj2a7vlzhvz0aqhn82mcf72lp8r3a7-zombienet/packages/orchestrator/dist/providers/native/nativeClient.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
┌────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Node'              │ /tmp/zombie-9739371c38cee8945a1ec83410dd6a3c_-20963-ZvceLXDqoFwh/logs                              │
│ s logs:            │                                                                                                    │
│ m                  │                                                                                                    │
└────────────────────┴────────────────────────────────────
```

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/757125/206528202-95ddf318-9ffd-40df-af32-198c4b3643da.png">

Log is empty.

**Comment by dzmitry-lahoda** [comment]
@pepoviola you can get error locally easy

https://docs.composable.finance/nix/install

```
nix run "github:ComposableFi/composable/10dbe1c86#zombienet-all-dev-local" -L  --option sandbox false --show-trace
```

**Comment by pepoviola** [comment]
Hi @dzmitry-lahoda, thanks for reporting. Can you run this command locally and check the output

```bash
/nix/store/j33may0jyxyg2v89k7cixipfam0gz5f8-acala/bin/acala --name bob-2 --node-key a9137698d8d3fdbf27efcdc8cd372084b52d484e8db866c5455bbb3f85299b54 --chain /tmp/zombie-9739371c38cee8945a1ec83410dd6a3c_-20963-ZvceLXDqoFwh/bob-2/cfg/karura-dev_rococo-local-2000.json --base-path /tmp/zombie-9739371c38cee8945a1ec83410dd6a3c_-20963-ZvceLXDqoFwh/bob-2/data --listen-addr /ip4/0.0.0.0/tcp/42449/ws --rpc-port 43289 --ws-port 35403 --prometheus-external --prometheus-port 35057 --rpc-cors all --unsafe-rpc-external --rpc-methods unsafe --unsafe-ws-external --collator -- --chain /tmp/zombie-9739371c38cee8945a1ec83410dd6a3c_-20963-ZvceLXDqoFwh/bob-2/cfg/rococo-local.json --execution wasm --port 44679 --ws-port 36833 --rpc-port 43399
```

Thanks!

**Comment by dzmitry-lahoda** [comment]
Weird. It works alone. Will take a look. Thanks.
